name: semRelease

on:
  push:
    branches:
      - main

jobs:
  semRelease:
    runs-on: ubuntu-latest
    steps:
      # Checkout code with Token
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_PAT }} # Ensure GITHUB_PAT is set as a repository secret
          ssh-strict: true
          persist-credentials: true
          clean: true
          fetch-depth: 1
          lfs: false
          submodules: false
          set-safe-directory: true

      # Setup Git
      - name: Setup Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.event.pusher.email || 'actions@github.com' }}"
