name: semRelease

on:
  push:
    branches:
      - main

jobs:
  semRelease:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code with Token
        uses: actions/checkout
        with:
          token: ${{ secrets.PAT }}
      
      - name: Setup git
        run: |
          git config --global user.name @${{github.actor}}
          git config --global user.email @${{github.mail}}

        
      
          
