name: semRelease

on:
  push:
    branches:
      - main

jobs:
  semRelease:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code with Token
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_PAT }}

      - name: Setup Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.event.pusher.email || 'actions@github.com' }}"
